services:
  # Služba pro databázi PostgreSQL
  database:
    image: postgres:15  # Používáme oficiální Docker image PostgreSQL verze 15
    environment:
      POSTGRES_USER: ${DATABASE_USER}      # Uživatelské jméno pro databázi (z .env souboru)
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}  # Heslo pro databázi (z .env souboru)
      POSTGRES_DB: ${DATABASE}             # Název databáze (z .env souboru)
    ports:
      - 5432:5432  # Mapování portu PostgreSQL na hostitelský systém
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data  # Uchování dat databáze i po restartu kontejneru
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USER}", "-d", "${DATABASE}"]  # Kontrola dostupnosti DB
      interval: 10s  # Kontrola se provádí každých 10 sekund
      timeout: 5s    # Maximální doba čekání na odpověď
      retries: 5     # Počet opakování testu před označením databáze jako nedostupné


  database-migration:
    build: .
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    command: >
      sh -c "
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py createsuperuser --username admin --email muj_osobni_email@gmail.com --noinput ; echo 0"
    depends_on:
      database:
        condition: service_healthy
  # Služba pro webovou aplikaci
  #
  web:
    build: .
    command: sh -c "
      service cron start &&
      python manage.py crontab add &&
      python manage.py runserver 0.0.0.0:80"
    volumes:
      - ./:/usr/src/app
      - ./public/:/usr/src/public
    ports:
      - 80:80
    env_file:
      - .env
    depends_on:
      database-migration:
        condition: service_completed_successfully
# Definice svazku pro uchování dat databáze
volumes:
  postgres_data:
