# Generated by Django 5.0.2 on 2025-04-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('calendar_name', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Birthdays',
                'ordering': ['birth_date'],
                'unique_together': {('name', 'birth_date')},
            },
        ),
    ]
