"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-!7u*-$#=h_tz#ak5i%k7e1pdwk0j4war-5n%0zgmy_tj1a#9+z"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

ASGI_APPLICATION = "django_project.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
        },
    },
}

# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "hello_world",
    "crossroad",
    "habit_tracker_1",
    "habit_tracker_2",
    "blog",
    "tailwind",
    "theme",
    "users",
    "birthday",
    "django_crontab",
    "chat",
    "library_rest",
    "library_graph",
    "library_rpc",
    'graphene_django',
    # "django_browser_reload",
]
TAILWIND_APP_NAME = 'theme'

# URL adresa pro přihlášení
# Když se nepřihlášený uživatel pokusí přistoupit k chráněné stránce, bude přesměrován sem
LOGIN_URL = '/users/login/'

# URL adresa pro registraci nových uživatelů
# Používá se pro odkazy na registrační formulář
REGISTER_URL = '/users/register/'

# URL adresa pro přesměrování po odhlášení
# Po úspěšném odhlášení bude uživatel přesměrován na přihlašovací stránku
LOGOUT_REDIRECT_URL = '/users/login/'

# URL adresa pro přesměrování po přihlášení
# Po úspěšném přihlášení bude uživatel přesměrován na hlavní stránku
# Prázdné '/' znamená kořenovou URL adresu webu (homepage)
LOGIN_REDIRECT_URL = '/'

INTERNAL_IPS = [
    "127.0.0.1",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "middleware.custom.LoginRequiredMiddleware", # nové
    "middleware.custom.Redirect404Middleware", # nové

    # "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = "django_project.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "django_project.wsgi.application"

# Použití SMTP backendu pro odesílání skutečných emailů
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# SMTP server Gmailu (lze změnit podle poskytovatele emailu)
EMAIL_HOST = 'smtp.gmail.com'
# Port pro TLS šifrovanou komunikaci
EMAIL_PORT = 587
# Aktivace TLS šifrování pro bezpečnou komunikaci
EMAIL_USE_TLS = True
# Přihlašovací email - načítá se z proměnných prostředí
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
# Heslo k emailu nebo aplikační heslo pro Gmail - načítá se z proměnných prostředí
# Pro Gmail je nutné použít aplikační heslo kvůli dvoufázovému ověření
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
# Výchozí emailová adresa odesílatele - používá stejný email jako pro přihlášení
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
CRONJOBS = [
    # # Každý den o půlnoci kontroluje narozeniny a posílá upozornění
    # ('0 0 * * *', 'birthday.cron.send_birthday_emails'),
    #
    # # Testovací úloha spouštěná každou minutu
    # # Slouží pro ověření, že cron správně běží
    # ('* * * * *', 'birthday.cron.test_cron_job'),
    #
    # # Testovací odesílání emailů každou minutu
    # # Pouze pro vývojové účely
    # ('* * * * *', 'birthday.mail.test_mail'),
    # ('0 0 * * *', 'birthday.cron.send_nameday_emails'),
]
CRONTAB_COMMAND_SUFFIX = '>> /var/log/cron.log 2>&1'  # napomáhá správnému logování

DATABASES = {
	"default": {
		"ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
		"NAME": os.environ.get("DATABASE", BASE_DIR / "db.sqlite3"),
		"USER": os.environ.get("DATABASE_USER", "user"),
		"PASSWORD": os.environ.get("DATABASE_PASSWORD", "password"),
		"HOST": os.environ.get("DATABASE_HOST", "localhost"),
		"PORT": os.environ.get("DATABASE_PORT", "5432"),
	}
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "public" / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
GRAPHENE = {
    'SCHEMA': 'library_graph.schema.schema'
}
